name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commitlint:
    name: Commitlint conventions
    uses: ./.github/workflows/commits.yaml

  code-quality:
    name: Code Quality
    uses: ./.github/workflows/format.yaml

  release:
    name: Release
    needs: [commitlint, code-quality]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: pnpm i

      - name: Build project
        run: |
          pnpm build
          cd apps/backend
          zip -r transactions-backend.zip . -x '*.git*' -x 'node_modules/*'
      
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          region: ${{ secrets.AWS_REGION }}
          use_existing_version_if_available: true
          application_name: ${{ secrets.AWS_APPLICATION_NAME }}
          version_label: ${{ secrets.AWS_APPLICATION_NAME }}-${{ github.sha }}
          deployment_package: transactions-backend.zip
          environment_name: ${{ secrets.AWS_ENVIRONMENT_NAME }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}