name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commitlint:
    name: Commitlint conventions
    uses: ./.github/workflows/commits.yaml

  code-quality:
    name: Code Quality
    uses: ./.github/workflows/format.yaml

  test:
    name: Test
    uses: ./.github/workflows/test.yaml

  release:
    name: Release
    needs: [commitlint, code-quality, test]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: pnpm i

      - name: Login to docker.io
        run: docker login --username ${{ secrets.DOCKER_HUB_USER }} --password ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract folder name from image name
        id: extract_folder_name
        run: |
          FOLDER_NAME=$(echo aws-backend | sed -E 's/^(.*?)-.*$/\1/' | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=folder_name::$FOLDER_NAME"

      - name: Build Docker image
        run: |
          DOCKERFILE_PATH="./apps/backend/Dockerfile"
          DOCKER_TAG="${{ secrets.DOCKER_HUB_USER }}/transactions-backend"
          DOCKER_DEFAULT_PLATFORM=linux/amd64 docker build -t $DOCKER_TAG -f $DOCKERFILE_PATH .

      - name: Push docker image
        run: docker push ${{ secrets.DOCKER_HUB_USER }}/transactions-backend